# Generated by Django 2.0.4 on 2018-04-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180418_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='captions',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
